# Generated by Django 4.2.13 on 2024-06-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="video_file",
            new_name="video",
        ),
        migrations.RemoveField(
            model_name="alert",
            name="alert_type",
        ),
        migrations.RemoveField(
            model_name="video",
            name="description",
        ),
        migrations.AddField(
            model_name="alert",
            name="severity",
            field=models.CharField(default="Low", max_length=50),
        ),
        migrations.AddField(
            model_name="video",
            name="detected_objects",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="lane_violations",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="system_performance",
            field=models.CharField(default="Good", max_length=50),
        ),
        migrations.AddField(
            model_name="video",
            name="traffic_density",
            field=models.CharField(default="Low", max_length=50),
        ),
        migrations.AlterField(
            model_name="alert",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
